import type { Property, SuggestedPrompt, Testimonial } from "@/types"

const img = (id: number) =>
  `https://picsum.photos/seed/${id}/800/600`

const agentImg = (id: number) =>
  `https://i.pravatar.cc/150?u=${id}`

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    title: "Modern Waterfront Villa with Bay Views",
    slug: "modern-waterfront-villa",
    price: 2495000,
    priceLabel: "$2,495,000",
    currency: "USD",
    address: "42 Oceanview Drive",
    city: "San Francisco",
    state: "CA",
    zip: "94102",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4200,
    lotSize: "0.35 acres",
    yearBuilt: 2022,
    type: "villa",
    listingType: "sale",
    description:
      "Stunning contemporary villa perched on the Pacific coastline with panoramic bay views. Floor-to-ceiling windows flood the open-plan living spaces with natural light. The chef's kitchen features marble countertops, Miele appliances, and a waterfall island. The primary suite occupies the entire upper level with a spa-like bathroom and private terrace. Smart home automation throughout.",
    features: [
      "Smart home automation",
      "Heated infinity pool",
      "Wine cellar",
      "Home theater",
      "EV charging station",
      "Rooftop terrace",
      "Private dock access",
      "Walk-in closets",
    ],
    images: [img(101), img(102), img(103), img(104)],
    status: "available",
    agentName: "Sarah Martinez",
    agentPhoto: agentImg(1),
    agentPhone: "+1 (415) 555-0101",
    agentEmail: "sarah.m@terravista.com",
    latitude: 37.7749,
    longitude: -122.4194,
    listedDate: "2025-12-01",
  },
  {
    id: "prop-2",
    title: "Downtown Luxury Penthouse",
    slug: "downtown-luxury-penthouse",
    price: 12000,
    priceLabel: "$12,000/mo",
    currency: "USD",
    address: "200 Park Avenue, PH1",
    city: "New York",
    state: "NY",
    zip: "10017",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2800,
    yearBuilt: 2020,
    type: "apartment",
    listingType: "rent",
    description:
      "Exclusive penthouse in the heart of Manhattan with sweeping skyline views. This triple-exposure residence features 12-foot ceilings, a private elevator landing, and an expansive great room. The chef's kitchen is appointed with custom cabinetry, Calacatta marble, and a professional-grade appliance suite. Primary suite includes a dressing room and en-suite marble bath with soaking tub.",
    features: [
      "Private elevator",
      "Doorman 24/7",
      "Rooftop pool",
      "Fitness center",
      "Valet parking",
      "Concierge service",
      "Private storage",
    ],
    images: [img(201), img(202), img(203), img(204)],
    status: "available",
    agentName: "James Chen",
    agentPhoto: agentImg(2),
    agentPhone: "+1 (212) 555-0202",
    agentEmail: "james.c@terravista.com",
    latitude: 40.7484,
    longitude: -73.9967,
    listedDate: "2026-01-15",
  },
  {
    id: "prop-3",
    title: "Mid-Century Modern Family Home",
    slug: "mid-century-modern-home",
    price: 875000,
    priceLabel: "$875,000",
    currency: "USD",
    address: "1847 Elmwood Avenue",
    city: "Austin",
    state: "TX",
    zip: "78701",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3100,
    lotSize: "0.28 acres",
    yearBuilt: 1965,
    type: "house",
    listingType: "sale",
    description:
      "Meticulously restored mid-century modern home in Austin's coveted Zilker neighborhood. Original architectural details blend seamlessly with modern updates including a renovated kitchen, new HVAC, and updated bathrooms. Open floor plan with floor-to-ceiling windows overlooking a private, landscaped backyard with mature oak trees. Walking distance to South Congress and Lady Bird Lake.",
    features: [
      "Original hardwood floors",
      "Updated kitchen",
      "Saltwater pool",
      "Detached studio/office",
      "Covered patio",
      "Smart thermostat",
      "Rainwater collection",
    ],
    images: [img(301), img(302), img(303), img(304)],
    status: "available",
    agentName: "David Kim",
    agentPhoto: agentImg(3),
    agentPhone: "+1 (512) 555-0303",
    agentEmail: "david.k@terravista.com",
    latitude: 30.2672,
    longitude: -97.7431,
    listedDate: "2026-02-01",
  },
  {
    id: "prop-4",
    title: "Beachfront Condo with Private Terrace",
    slug: "beachfront-condo-terrace",
    price: 5500,
    priceLabel: "$5,500/mo",
    currency: "USD",
    address: "888 Collins Avenue, #1204",
    city: "Miami Beach",
    state: "FL",
    zip: "33139",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1500,
    yearBuilt: 2019,
    type: "condo",
    listingType: "rent",
    description:
      "Luxurious beachfront condo with direct ocean views from every room. Floor-to-ceiling sliding glass doors open to a wraparound terrace perfect for entertaining. The interior features European white oak flooring, a designer kitchen with Sub-Zero and Wolf appliances, and spa-inspired bathrooms. Building amenities include infinity pool, fitness center, and beach service.",
    features: [
      "Ocean views",
      "Wraparound terrace",
      "Infinity pool",
      "Beach service",
      "Spa & sauna",
      "Wine room",
      "Valet parking",
    ],
    images: [img(401), img(402), img(403), img(404)],
    status: "available",
    agentName: "Elena Rodriguez",
    agentPhoto: agentImg(4),
    agentPhone: "+1 (305) 555-0404",
    agentEmail: "elena.r@terravista.com",
    latitude: 25.7826,
    longitude: -80.134,
    listedDate: "2026-01-20",
  },
  {
    id: "prop-5",
    title: "Historic Brownstone in Park Slope",
    slug: "historic-brownstone-park-slope",
    price: 4200000,
    priceLabel: "$4,200,000",
    currency: "USD",
    address: "246 Prospect Park West",
    city: "Brooklyn",
    state: "NY",
    zip: "11215",
    bedrooms: 6,
    bathrooms: 4,
    sqft: 4800,
    lotSize: "0.04 acres",
    yearBuilt: 1899,
    type: "townhouse",
    listingType: "sale",
    description:
      "Magnificent limestone-clad brownstone on one of Park Slope's most coveted blocks. This 20-foot-wide residence has been lovingly restored while preserving its original 19th-century craftsmanship: plaster moldings, marble fireplaces, inlaid hardwood floors, and a sweeping central staircase. The garden level opens to a private south-facing patio and landscaped garden.",
    features: [
      "Original woodwork",
      "Marble fireplaces (4)",
      "Chef's kitchen",
      "Private garden",
      "Wine cellar",
      "Roof deck",
      "Central AC",
    ],
    images: [img(501), img(502), img(503), img(504)],
    status: "available",
    agentName: "Marcus Williams",
    agentPhoto: agentImg(5),
    agentPhone: "+1 (718) 555-0505",
    agentEmail: "marcus.w@terravista.com",
    latitude: 40.6782,
    longitude: -73.9813,
    listedDate: "2026-02-15",
  },
  {
    id: "prop-6",
    title: "Contemporary Lake House Retreat",
    slug: "contemporary-lake-house",
    price: 1625000,
    priceLabel: "$1,625,000",
    currency: "USD",
    address: "782 Lakeshore Drive",
    city: "Seattle",
    state: "WA",
    zip: "98102",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3500,
    lotSize: "0.5 acres",
    yearBuilt: 2021,
    type: "house",
    listingType: "sale",
    description:
      "Architect-designed contemporary retreat on Lake Washington with mountain views. The open-concept main level features a great room with 20-foot ceilings, a floor-to-ceiling stone fireplace, and walls of glass that disappear into the screened porch. Gourmet kitchen with waterfall quartz island and butler's pantry. Primary suite with spa bath, soaking tub, and private deck.",
    features: [
      "Lake frontage",
      "Private dock",
      "Screened porch",
      "Home office",
      "Mudroom",
      "Generator backup",
      "Boat lift",
    ],
    images: [img(601), img(602), img(603), img(604)],
    status: "available",
    agentName: "Olivia Park",
    agentPhoto: agentImg(6),
    agentPhone: "+1 (206) 555-0606",
    agentEmail: "olivia.p@terravista.com",
    latitude: 47.6062,
    longitude: -122.3321,
    listedDate: "2026-01-10",
  },
  {
    id: "prop-7",
    title: "Mountain View Eco- Estate",
    slug: "mountain-view-eco-estate",
    price: 5800,
    priceLabel: "$5,800/mo",
    currency: "USD",
    address: "45 Aspen Ridge Road",
    city: "Boulder",
    state: "CO",
    zip: "80302",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3200,
    lotSize: "2.5 acres",
    yearBuilt: 2023,
    type: "house",
    listingType: "rent",
    description:
      "Net-zero energy smart home perched on a ridge with sweeping Flatiron views. Solar panels, geothermal heating, and a green roof make this one of Colorado's most sustainable luxury rentals. The open interior features reclaimed barn wood accents, polished concrete floors with radiant heating, and a chef's kitchen with induction cooking.",
    features: [
      "Net-zero energy",
      "Solar panels",
      "Geothermal HVAC",
      "EV charger",
      "Smart irrigation",
      "Trail access",
      "Hot tub",
    ],
    images: [img(701), img(702), img(703), img(704)],
    status: "available",
    agentName: "Ryan Torres",
    agentPhoto: agentImg(7),
    agentPhone: "+1 (303) 555-0707",
    agentEmail: "ryan.t@terravista.com",
    latitude: 40.015,
    longitude: -105.2705,
    listedDate: "2026-02-20",
  },
  {
    id: "prop-8",
    title: "Golf Course Villa in Paradise Valley",
    slug: "golf-course-villa-paradise-valley",
    price: 3850000,
    priceLabel: "$3,850,000",
    currency: "USD",
    address: "17890 Desert Fairway Drive",
    city: "Scottsdale",
    state: "AZ",
    zip: "85255",
    bedrooms: 5,
    bathrooms: 5,
    sqft: 5600,
    lotSize: "1.2 acres",
    yearBuilt: 2020,
    type: "villa",
    listingType: "sale",
    description:
      "Exquisite Tuscan-inspired villa on the 14th fairway of the TPC Scottsdale Champions Course. This entertainer's paradise features a gourmet kitchen, two islands, and a caterer's prep kitchen. The outdoor living area is spectacular with a负 edge pool, outdoor kitchen, fireplace, and putting green. The primary suite offers dual bathrooms and a private courtyard.",
    features: [
      "Golf course frontage",
      "Infinity edge pool",
      "Outdoor kitchen",
      "Putting green",
      "Casita/guest house",
      "Wine grotto",
      "Home gym",
    ],
    images: [img(801), img(802), img(803), img(804)],
    status: "available",
    agentName: "Sarah Martinez",
    agentPhoto: agentImg(1),
    agentPhone: "+1 (480) 555-0808",
    agentEmail: "sarah.m@terravista.com",
    latitude: 33.5091,
    longitude: -111.8988,
    listedDate: "2025-11-15",
  },
  {
    id: "prop-9",
    title: "Industrial Loft in Arts District",
    slug: "industrial-loft-arts-district",
    price: 3200,
    priceLabel: "$3,200/mo",
    currency: "USD",
    address: "750 Traction Avenue, #310",
    city: "Los Angeles",
    state: "CA",
    zip: "90013",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 1400,
    yearBuilt: 2018,
    type: "apartment",
    listingType: "rent",
    description:
      "Converted warehouse loft in the heart of the LA Arts District with exposed brick, polished concrete floors, and 16-foot ceilings with original timber beams. A custom steel and glass wall separates the sleeping area from the living space. The kitchen features stainless steel appliances, quartz countertops, and a breakfast bar.",
    features: [
      "Exposed brick",
      "Timber beams",
      "In-unit laundry",
      "Rooftop deck",
      "Package room",
      "Bike storage",
      "Pet friendly",
    ],
    images: [img(901), img(902), img(903), img(904)],
    status: "available",
    agentName: "James Chen",
    agentPhoto: agentImg(2),
    agentPhone: "+1 (213) 555-0909",
    agentEmail: "james.c@terravista.com",
    latitude: 34.05,
    longitude: -118.2399,
    listedDate: "2026-02-10",
  },
  {
    id: "prop-10",
    title: "French Chateau-Style Estate",
    slug: "french-chateau-estate",
    price: 12500000,
    priceLabel: "$12,500,000",
    currency: "USD",
    address: "1 Chateau Lane",
    city: "Beverly Hills",
    state: "CA",
    zip: "90210",
    bedrooms: 7,
    bathrooms: 8,
    sqft: 9500,
    lotSize: "2 acres",
    yearBuilt: 2015,
    type: "villa",
    listingType: "sale",
    description:
      "A masterpiece of French neoclassical architecture set behind private gates on two acres of manicured gardens. This 7-bedroom estate features a grand salon with 30-foot domed ceiling, a formal dining room seating 24, a paneled library, and a full-service spa. The grounds include a tennis court, pool pavilion, and a 2-bedroom guest house.",
    features: [
      "Tennis court",
      "Guest house",
      "Home spa",
      "Wine cellar",
      "Library",
      "Pool pavilion",
      "Gated entry",
      "Helipad",
    ],
    images: [img(1001), img(1002), img(1003), img(1004)],
    status: "available",
    agentName: "Sarah Martinez",
    agentPhoto: agentImg(1),
    agentPhone: "+1 (310) 555-1010",
    agentEmail: "sarah.m@terravista.com",
    latitude: 34.0736,
    longitude: -118.4004,
    listedDate: "2026-01-05",
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: "t-1",
    name: "Jennifer Walsh",
    role: "Home Buyer, San Francisco",
    content:
      "TerraVista made finding our dream home effortless. The AI matched us with properties we never would have found on our own. Their agents were knowledgeable and truly cared about our needs.",
    rating: 5,
    avatar: agentImg(10),
  },
  {
    id: "t-2",
    name: "Michael Torres",
    role: "Property Investor, Austin",
    content:
      "As an investor, the market intelligence TerraVista provides is invaluable. I closed three deals in my first month using their platform — the data-driven approach is a game changer.",
    rating: 5,
    avatar: agentImg(11),
  },
  {
    id: "t-3",
    name: "Priya Sharma",
    role: "Luxury Renter, NYC",
    content:
      "We found our Manhattan penthouse through TerraVista. The virtual tours and detailed neighborhood insights helped us make the right decision without endless in-person visits.",
    rating: 5,
    avatar: agentImg(12),
  },
  {
    id: "t-4",
    name: "Robert Chen",
    role: "First-Time Buyer, Denver",
    content:
      "I was nervous about buying my first home, but the TerraVista team guided me through every step. The AI chatbot answered my questions at 10 PM on a Sunday — incredible service.",
    rating: 5,
    avatar: agentImg(13),
  },
]

export const mockPromptSuggestions: SuggestedPrompt[] = [
  { id: "p1", text: "Find me 3-bedroom homes under $800k" },
  { id: "p2", text: "What's the property tax rate in Austin?" },
  { id: "p3", text: "Compare schools near downtown Seattle" },
  { id: "p4", text: "Schedule a viewing for the penthouse" },
  { id: "p5", text: "How do interest rates affect my mortgage?" },
  { id: "p6", text: "Show me investment properties in Miami" },
]

export const cityListings = [
  { city: "San Francisco", count: 124, image: img(111) },
  { city: "New York", count: 312, image: img(211) },
  { city: "Austin", count: 89, image: img(311) },
  { city: "Miami", count: 178, image: img(411) },
  { city: "Seattle", count: 95, image: img(611) },
  { city: "Los Angeles", count: 246, image: img(911) },
]

export const blogPosts = [
  {
    id: "b-1",
    title: "2026 Real Estate Market Forecast: What Buyers Need to Know",
    excerpt:
      "Interest rates, inventory levels, and emerging neighborhood trends that will define the housing market this year.",
    image: img(150),
    date: "Mar 15, 2026",
    category: "Market Insights",
    author: "Sarah Martinez",
  },
  {
    id: "b-2",
    title: "The Rise of AI in Real Estate: How Smart Tech Is Changing Home Buying",
    excerpt:
      "From AI-powered property matching to predictive pricing, technology is revolutionizing how we buy and sell homes.",
    image: img(250),
    date: "Mar 10, 2026",
    category: "Technology",
    author: "David Kim",
  },
  {
    id: "b-3",
    title: "Top 10 Neighborhoods for Remote Workers in 2026",
    excerpt:
      "Affordable homes, fast internet, and great quality of life — these communities are perfect for the remote workforce.",
    image: img(350),
    date: "Mar 5, 2026",
    category: "Lifestyle",
    author: "Elena Rodriguez",
  },
]
